### ISSUE TITLE
Application data

### ISSUE THREAD

**Issue by temaivanoff** [nodertc/nodertc#1]
Добрый день, попробовал пример с браузером, сессия webrtc  поднимается, в браузере срабатывает евент `open`, браузер шлёт данные, на клиенте ноде вижу что по dtls пришли данные (aplication data).
Я как понимаю теперь нужно реализовать `srtp` ?
Можете написать, что осталось сделать для минимальной рабочей версии, спасибо.

**Comment by reklatsmasters** [comment]
@fast0490f Здравствуйте. По идее для рабочего прототипа нужно слегка подправить модуль sctp и реализовать datachannel протокол.

До этого я хочу подправить производительность у binary-data (сейчас этим занимаюсь), после этого планирую значительно переработать модуль sctp и только после этого будет реализован datachannel и прототип.

**Comment by temaivanoff** [comment]
@reklatsmasters спасибо за разъяснения, если у Вас описание реализации протокола webrtc на русском языке, интересуют технические детали.
Можете ли Вы написать в общих чертах как реализуется стек, шифрование и участие sdp 
на примере Алисы и Боба?

**Comment by reklatsmasters** [comment]
@fast0490f Вам лучше обратиться к первоисточнику - спецификациям:

* [WebRTC 1.0: Real-time Communication Between Browsers](https://w3c.github.io/webrtc-pc/)
* [WebRTC Data Channels](https://tools.ietf.org/html/draft-ietf-rtcweb-data-channel-13)
* [WebRTC Data Channel Establishment Protocol](https://tools.ietf.org/html/draft-ietf-rtcweb-data-protocol-09)
* [Datagram Transport Layer Security Version 1.2](https://tools.ietf.org/html/rfc6347)
* [The Transport Layer Security (TLS) Protocol Version 1.2](https://tools.ietf.org/html/rfc5246)
* [Stream Control Transmission Protocol](https://tools.ietf.org/html/rfc4960)
* [Session Traversal Utilities for NAT (STUN)](https://tools.ietf.org/html/rfc5389)
* [SDP: Session Description Protocol](https://tools.ietf.org/html/rfc4566)

Вот базовый список спецификаций WebRTC. Описания работы технологии есть практически в каждом докладе про WebRTC. Даже на хабре пару статей есть на эту тему.

**Comment by temaivanoff** [comment]
@reklatsmasters спасибо, боьшое
