### ISSUE TITLE
What is the principle?No native lib？

### ISSUE THREAD

**Issue by zsmweb** [nodertc/nodertc#3]
I want to know what the principle of implementation is. No documentation is seen here.

**Comment by zsmweb** [comment]
Dose it support  turn server? How to config it? Thanks!

**Comment by reklatsmasters** [comment]
The main idea is to make pure js webrtc server. Native libraries are optional. 

Turn server is not supported yet.

**Comment by zsmweb** [comment]
Nice job! Thanks!
